### ISSUE TITLE
How was Private.SourceBuilt.Artifacts generated?

### ISSUE THREAD

**Issue by sec** [Thefrank/freebsd-dotnet-sourcebuild#1]
As title says, how to build this archive - is it somewhere in dotnet's repos?

**Comment by Thefrank** [comment]
yes. https://github.com/dotnet/dotnet/ generates it as a part of its output along with:
- updated `PackageVersions.props`
- a `prebuilt-report` output if it used more packages than listed or if packages went unused. If generated, make sure to verify everything is in order. It will remind of this as a part of build closure.
- `Private.SourceBuilt.Prebuilts` if something came in externally (e.g., fsharp)

**Comment by sec** [comment]
So it's the part of VMR build, is that needed to start the build, so how to bootstrap this for FreeBSD? :)

**Comment by Thefrank** [comment]
From net8RTM and beyond it can be completely offline sourcebuilt... after cloning repos and downloading artifacts. 
I did this: Crossbuild RC1 -> Sourcebuild RC2 using Crossbuilt RC1 SDK + extra items -> Sourcebuild RTM using Sourcebuilt RC2. Sourcebuild loop complete!

**Comment by sec** [comment]
Right, forgot I could do crossbuild :d Thanks.
